// Generated by CoffeeScript 1.4.0
/*
TwitterObserver
Ryhan Hassan | ryhanh@me.com
*/(function(){this.TwitterObserver=function(){function a(t,n){o=t;e=n}var e,t,n,r,i,s,o,u;s=0;o="";e=function(){return!1};a.prototype.watch=function(e){e==null&&(e=5e3);this.update();return setInterval(this.update,e)};a.prototype.update=function(){return t(r)};t=function(e){var t,n;t="http://search.twitter.com/search.json?";n="include_entities=true&q="+o+"&callback=?";return $.getJSON(t+n,e)};n=function(e){return(new Date(e)).getTime()};i=function(e){return n(e.created_at)>s};u=function(e){return{user:e.from_user,text:e.text}};r=function(t){var r;r=_.map(_.filter(t.results,i),u);s=_.max(_.map(_.pluck(t.results,"created_at"),n));if(r.length>0)return e(r)};return a}()}).call(this);